# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: helper
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changedit
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
